import { calculateStaffModifiers, staffRoleLabels } from "../engine/staffEngine.js";
import { money,pageHead,progress,userTeam } from "./helpers.js";

const topAttrs={team_principal:["leadership","moraleManagement"],technical_director:["technicalKnowledge","chassisKnowledge"],head_of_aero:["aerodynamics","dataAnalysis"],head_of_engine:["engineKnowledge","reliabilityFocus"],strategy_director:["raceStrategy","pressureManagement"],pit_crew_chief:["pitStopTraining","pressureManagement"],scouting_director:["scouting","dataAnalysis"],commercial_director:["commercial","negotiation"],fitness_coach:["pressureManagement","moraleManagement"],sports_psychologist:["moraleManagement","pressureManagement"]};
const label={leadership:"Liderazgo",technicalKnowledge:"Conocimiento técnico",aerodynamics:"Aero",engineKnowledge:"Motor",chassisKnowledge:"Chasis",raceStrategy:"Estrategia",dataAnalysis:"Datos",driverDevelopment:"Desarrollo pilotos",scouting:"Scouting",negotiation:"Negociación",commercial:"Comercial",moraleManagement:"Moral",pressureManagement:"Presión",reliabilityFocus:"Confiabilidad",pitStopTraining:"Pit stops"};

export function renderStaffScreen(world){
  const team=userTeam(world),staff=(world.staff??[]).filter(s=>s.teamId===team.id),mods=calculateStaffModifiers(team,world);
  return`${pageHead("Staff","Dirección técnica, deportiva y comercial del equipo")}
  <div class="grid four"><article class="card metric-card"><div class="metric-label">STAFF</div><div class="metric-value">${staff.length}</div><p>Miembros contratados</p></article><article class="card metric-card"><div class="metric-label">NÓMINA</div><div class="metric-value">${money(staff.reduce((a,b)=>a+(b.salary??0),0))}</div><p>Salario anual</p></article><article class="card metric-card"><div class="metric-label">I+D</div><div class="metric-value">${mods.aeroDevelopment+mods.engineDevelopment+mods.chassisDevelopment}</div><p>Modificador técnico</p></article><article class="card metric-card"><div class="metric-label">COMERCIAL</div><div class="metric-value">${mods.commercial}</div><p>Sponsors y acuerdos</p></article></div>
  <div class="grid two">${staff.map(member=>{const attrs=topAttrs[member.role]??["currentAbility","reputation"];return`<article class="card staff-card"><div class="card-title-row"><div><span class="pill">${staffRoleLabels[member.role]??member.role}</span><h3>${member.name}</h3><p>${member.nationality} · ${member.age} años · contrato ${member.contractUntil}</p></div><div class="overall-ring"><strong>${member.currentAbility}</strong><span>CA</span></div></div><div class="grid two compact-grid">${attrs.map(key=>progress(label[key]??key,member.attributes?.[key]??member[key]??member.currentAbility,key==="commercial"?"green":"blue")).join("")}</div><div class="contract-box"><div><span>Salario</span><strong>${money(member.salary??0)}</strong></div><div><span>Reputación</span><strong>${member.reputation}</strong></div><div><span>Potencial</span><strong>${member.potentialAbility}</strong></div></div></article>`}).join("")}</div>`;
}
