import { driverOverall,getCategoryState,getDriver,money,pageHead,progress,userTeam } from "./helpers.js";
import { avatar,badge,metricCard } from "./components.js";
import { contractStatus,renewalCost,roleLabels } from "../engine/contractEngine.js";

export function renderTeamScreen(world){
  const team=userTeam(world),drivers=team.drivers.map(id=>getDriver(world,id)).filter(Boolean);
  const position=getCategoryState(world,team.categoryId).teamStandings.find(row=>row.teamId===team.id)?.position??"â€”";
  const expiring=drivers.filter(d=>d.contractUntil<=world.currentSeason+1);
  return `<section class="team-banner" style="--team-color:${team.color}"><div><span class="kicker">${team.shortName} Â· TEAM HQ</span><h2>${team.name}</h2><p>DirecciÃ³n deportiva Â· ${world.categories.find(c=>c.id===team.categoryId)?.name}</p></div><div class="team-banner-score"><span>REPUTACIÃ“N</span><strong>${team.reputation}</strong></div></section>
  <div class="team-mobile-stack">
    <article class="card"><span class="metric-label">RESUMEN DEL EQUIPO</span><h3>${team.name}</h3><p>Constructores P${position} Â· reputaciÃ³n ${team.reputation} Â· paquete ${team.carPerformance}</p><button class="button full" data-action="go" data-screen="standings">Ver campeonato</button></article>
    <article class="card"><span class="metric-label">PILOTOS</span>${drivers.map(d=>`<div class="standing-line"><b>${driverOverall(d)}</b><span>${d.name}</span><strong>${contractStatus(d,world.currentSeason).label}</strong></div>`).join("")}</article>
    <article class="card"><span class="metric-label">COCHE</span>${progress("Rendimiento",team.carPerformance)}${progress("AerodinÃ¡mica",team.aerodynamics)}${progress("Motor",team.engine)}${progress("Confiabilidad",team.reliability,"green")}<button class="button full" data-action="go" data-screen="development">Ver ingenierÃ­a</button></article>
    <article class="card"><span class="metric-label">FINANZAS / CONTRATOS</span><p>Presupuesto ${money(team.budget)} Â· salarios ${money(team.salaryCommitted??0)}</p>${expiring.length?expiring.map(d=>`<div class="standing-line"><b>${d.contractUntil}</b><span>${d.name}</span><strong>vence</strong></div>`).join(""):`<p class="muted">Sin vencimientos urgentes.</p>`}<button class="button full" data-action="go" data-screen="finances">Ver finanzas</button></article>
  </div>
  <div class="grid four">${metricCard("Presupuesto",money(team.budget),"Fondos disponibles","good")}${metricCard("Salarios",money(team.salaryCommitted??0),"Compromiso anual")}${metricCard("PosiciÃ³n",position,"Campeonato de equipos")}${metricCard("Rendimiento",team.carPerformance,"Paquete actual")}</div>
  ${pageHead("Contratos","Pilotos actuales, salario, rol, estado y felicidad")}
  ${driverComparisonBlock(drivers)}
  <div class="table-wrap"><table class="data-table"><thead><tr><th>Piloto</th><th>Contrato hasta</th><th>Salario</th><th>Rol</th><th>Estado</th><th>Felicidad</th><th>Acciones</th></tr></thead><tbody>${drivers.map(driver=>{const contract=contractStatus(driver,world.currentSeason);return`<tr><td><button class="table-link" data-action="view-driver" data-driver="${driver.id}">${driver.name}</button></td><td>${driver.contractUntil}</td><td>${money(driver.salary??0)}</td><td>${roleLabels[driver.role]??driver.role}</td><td><span class="pill ${contract.tone}">${contract.label}</span></td><td>${driver.driverHappiness??driver.morale}/100</td><td><button class="button small" data-action="renew-driver" data-driver="${driver.id}">Renovar</button> <button class="button small danger" data-action="release-driver" data-driver="${driver.id}">Liberar</button></td></tr>`}).join("")||`<tr><td colspan="7" class="empty-cell">No hay pilotos con contrato.</td></tr>`}</tbody></table></div>
  ${pageHead("Pilotos titulares","Rendimiento y estado deportivo")}
  <div class="grid two">${drivers.map(driver=>{const contract=contractStatus(driver,world.currentSeason),cost=renewalCost(driver);return`<article class="card roster-card" style="--team-color:${team.color}"><div class="driver-profile-head">${avatar(driver,"large")}<div><span class="pill ${contract.tone}">${contract.label}</span><h2>${driver.name}</h2><p>${driver.nationality} Â· ${driver.age} aÃ±os Â· #${driver.number}</p></div><div class="overall-ring"><strong>${driverOverall(driver)}</strong><span>Rating</span></div></div><div class="grid two compact-grid">${progress("Velocidad",driver.attributes.speed)}${progress("Ritmo",driver.attributes.racePace)}${progress("Moral",driver.morale,"green")}${progress("Felicidad",driver.driverHappiness??driver.morale,"blue")}</div><div class="contract-box"><div><span>RenovaciÃ³n</span><strong>${money(cost)}</strong></div><div><span>Rol</span><strong>${roleLabels[driver.role]??driver.role}</strong></div><div class="actions"><button class="button small" data-action="renew-driver" data-driver="${driver.id}">Renovar +2 aÃ±os</button><button class="button small danger" data-action="release-driver" data-driver="${driver.id}">Liberar</button><button class="button small ghost" data-action="view-driver" data-driver="${driver.id}">Perfil</button></div></div></article>`}).join("")||`<article class="card notice">No hay pilotos titulares. VisitÃ¡ el mercado para completar el equipo.</article>`}</div>
  ${pageHead("Estructura deportiva","Personal clave y objetivos de temporada")}
  <div class="grid two"><article class="card"><div class="staff-grid"><div>${badge("DT")}<strong>Helena Ward</strong><span>Directora tÃ©cnica Â· 82</span></div><div>${badge("ING")}<strong>Rafael Costa</strong><span>Jefe de ingenierÃ­a Â· 78</span></div><div>${badge("EST")}<strong>Min-Jae Park</strong><span>Estratega principal Â· 80</span></div><div>${badge("PIT")}<strong>Owen Blake</strong><span>Jefe de boxes Â· ${team.pitCrew}</span></div></div></article><article class="card objectives"><div class="objective"><span>Objetivo deportivo</span><strong>Finalizar entre los ${Math.max(3,Math.ceil((100-team.reputation)/10)+3)} mejores</strong><em>En curso</em></div><div class="objective"><span>Objetivo tÃ©cnico</span><strong>Mejorar el rendimiento del auto</strong><em>+2 requerido</em></div><div class="objective"><span>Objetivo financiero</span><strong>Mantener balance positivo</strong><em class="good">Estable</em></div></article></div>
  ${pageHead("Atributos del coche","Estado actual del monoplaza")}<article class="card"><div class="grid two"><div>${progress("Rendimiento",team.carPerformance)}${progress("AerodinÃ¡mica",team.aerodynamics)}${progress("Motor",team.engine)}${progress("Chasis",team.chassis)}</div><div>${progress("Confiabilidad",team.reliability,"green")}${progress("Estrategia",team.strategy,"blue")}${progress("Pit crew",team.pitCrew)}${progress("Instalaciones",team.facilitiesLevel)}</div></div></article>`;
}

function driverComparisonBlock(drivers){
  const metrics=[["Clasificación","qualifying"],["Ritmo","racePace"],["Consistencia","consistency"],["Neumáticos","tyreManagement"],["Feedback","feedback"]];
  if(!drivers.length)return"";
  return `<article class="card driver-compare-card"><span class="metric-label">COMPARATIVA DE PILOTOS</span><h3>Lectura rápida del garaje</h3><div class="driver-compare-grid">${metrics.map(([label,key])=>`<div class="compare-row"><span>${label}</span>${drivers.map(driver=>{const value=driver.attributes?.[key]??driver[key]??0;return`<div class="compare-bar"><b>${driver.name.split(" ").at(-1)}</b><em style="--value:${value}%"></em><strong>${value}</strong></div>`}).join("")}</div>`).join("")}</div></article>`;
}

